name: CI/CD Workflow

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build Docker image
        run: mvn docker:build

      - name: Tag Docker image
        run: docker tag ${image.registry}/${image.name}:${image.tag} ${image.registry}/${image.name}:latest

      - name: Log in to Docker Registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_REGISTRY_USER }}
          password: ${{ secrets.DOCKER_REGISTRY_PAT }}

      - name: Push Docker image
        run: docker push ${image.registry}/${image.name}:latest

    env:
        image.registry: tambenikita391
        image.name: api-gateway
        image.tag: 0.0.1-SNAPSHOT
