name: CI/CD Workflow

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build Docker image
        run: docker build -t $IMAGE_REGISTRY/$IMAGE_NAME:$IMAGE_TAG .

      - name: Tag Docker image
        run: |
          docker tag $IMAGE_REGISTRY/$IMAGE_NAME:$IMAGE_TAG $IMAGE_REGISTRY/$IMAGE_NAME:latest

        env:
          IMAGE_REGISTRY: tambenikita391
          IMAGE_NAME: api-gateway
          IMAGE_TAG: 0.0.1-SNAPSHOT

      - name: Log in to Docker Registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_REGISTRY_USER }}
          password: ${{ secrets.DOCKER_REGISTRY_PAT }}

      - name: Push Docker image
        run: |
          docker push $IMAGE_REGISTRY/$IMAGE_NAME:latest
        env:
          IMAGE_REGISTRY: tambenikita391
          IMAGE_NAME: api-gateway
