name: CI/CD Workflow

on:
  push:
    branches:
      - main

jobs:
  pre-commit-scans:
    runs-on: ubuntu-latest
    
    steps:
    - name: Setup java
      uses: actions/setup-java@v4
      with:
         distribution: 'temurin' 
         java-version: '21'

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Perform google formatter check
      run: mvn com.spotify.fmt:fmt-maven-plugin:check

    - name: GitLeaks Scan
      uses: zricethezav/gitleaks-action@v1.3.0
      with:
        args: --path=.

    - name: OSS Scan
      run: mvn ossindex:audit
      continue-on-error: true

    - name: OWASP Scan
      if: false
      run: mvn org.owasp:dependency-check-maven:check

    - name: Build code and create Docker image
      run: mvn clean install io.fabric8:docker-maven-plugin:build

    - name: Re tag docker image
      run: docker tag dnyanyog.org/api-gateway:0.0.1-SNAPSHOT tambenikita391/api-gateway:latest

    - name: Log in to GitHub Docker Registry
      uses: docker/login-action@v2
      with:
        username: ${{secrets.DOCKER_REGISTRY_USER}}
        password: ${{secrets.DOCKER_REGISTRY_PAT}}

    - name: Push docker images
      run: docker push  tambenikita391/api-gateway:latest
       
